import type { AreaView, EditableResourceDocument, FeatureKind, MobileView, RoomView } from "./types";

export const navItems = [
  { id: "classes" as FeatureKind, label: "Classes" },
  { id: "races" as FeatureKind, label: "Races" },
  { id: "helps" as FeatureKind, label: "Help" },
  { id: "notes" as FeatureKind, label: "Notes" },
  { id: "game" as FeatureKind, label: "Game" },
];

export const areaNavItem = { id: "areas" as FeatureKind, label: "Areas" };

export const areaChildNavItems = [
  { id: "rooms" as FeatureKind, label: "Rooms" },
  { id: "mobiles" as FeatureKind, label: "Mobiles" },
  { id: "items" as FeatureKind, label: "Items" },
  { id: "shops" as FeatureKind, label: "Shops" },
  { id: "resets" as FeatureKind, label: "Resets" },
];

export const mobileChildNavItems = [
  { id: "specials" as FeatureKind, label: "Specials" },
];

export const abilitiesNavItem = { label: "Abilities" };

export const abilityChildNavItems = [
  { id: "commands" as FeatureKind, label: "Commands" },
  { id: "spells" as FeatureKind, label: "Spells" },
  { id: "skills" as FeatureKind, label: "Skills" },
  { id: "socials" as FeatureKind, label: "Emotes" },
];

export const emptyAreaDraft: AreaView = {
  author: "",
  name: "",
  vnum: "",
  suggestedLevelRange: "",
  rooms: [],
  mobiles: [],
  objects: [],
  shops: [],
  resets: [],
  specials: [],
};

export const areaListFields = ["rooms", "mobiles", "objects", "shops", "resets", "specials"] as const;

export const emptyRoomDraft: RoomView = {
  areaId: "",
  vnum: "",
  name: "",
  description: "",
  extraDescription: "",
  pvp: false,
  spawn: false,
  spawnTimer: 0,
  spawnTime: 0,
  teleDelay: 0,
  roomFlags: 0,
  sectorType: 0,
  exits: [],
  mobiles: {},
};

export const roomNumberFields = ["spawnTimer", "spawnTime", "teleDelay", "roomFlags", "sectorType"] as const;

export const directionNames = ["north", "east", "south", "west", "up", "down"];
export const editableResourceKinds: FeatureKind[] = ["items", "shops", "resets", "specials"];
export const topLevelEditableResourceKinds: FeatureKind[] = [
  "classes",
  "races",
  "skills",
  "spells",
  "commands",
  "socials",
  "helps",
];
export const areaScopedDraftKinds: FeatureKind[] = ["areas", "rooms", "mobiles", ...editableResourceKinds];

export const emptyMobileDraft: MobileView = {
  areaId: "",
  vnum: "",
  name: "",
  shortDescription: "",
  longDescription: "",
  description: "",
  race: "",
  level: 0,
  hitDice: "",
  damageDice: "",
  flags: 0,
  statusFlags: 0,
};

export const preferredMobileFields = [
  "id",
  "areaId",
  "vnum",
  "name",
  "shortDescription",
  "longDescription",
  "description",
  "race",
  "level",
  "hitDice",
  "damageDice",
  "flags",
  "statusFlags",
];

export const emptyEditableResourceDrafts: Record<string, EditableResourceDocument> = {
  items: {
    areaId: "",
    vnum: "",
    name: "",
    shortDescription: "",
    longDescription: "",
    material: "",
    itemType: "",
    extraFlags: "",
    wearFlags: "",
    value0: "",
    value1: "",
    value2: "",
    value3: "",
    value4: "",
    level: 0,
    weight: 0,
    cost: 0,
    condition: "",
    affectData: [],
    extraDescription: [],
  },
  shops: {
    areaId: "",
    keeper: 0,
    buyType0: 0,
    buyType1: 0,
    buyType2: 0,
    buyType3: 0,
    buyType4: 0,
    profitBuy: 0,
    profitSell: 0,
    openHour: 0,
    closeHour: 0,
    comment: "",
  },
  resets: {
    areaId: "",
    command: "",
    arg1: "",
    arg2: "",
    arg3: "",
    arg4: "",
    comment: "",
  },
  specials: {
    areaId: "",
    mobVnum: "",
    name: "",
    comment: "",
    specialFunction: [],
  },
  classes: {
    name: "",
    whoName: "",
    primaryAttribute: "",
    startingWeapon: "",
    baseGroup: "",
    defaultGroup: "",
    skillAdept: 0,
    thac0_00: 0,
    thac0_32: 0,
    hpMin: 0,
    hpMax: 0,
    fMana: false,
  },
  races: {
    name: "",
    size: "",
    skills: [],
    classMultiplier: [],
    points: 0,
    str: 0,
    maxStr: 0,
    INT: 0,
    maxInt: 0,
    con: 0,
    maxCon: 0,
    wis: 0,
    maxWis: 0,
    dex: 0,
    maxDex: 0,
  },
  skills: {
    name: "",
    kind: "skill",
    handlerId: "",
    target: "",
    minPosition: "",
    nounDamage: "",
    fightExecutor: "",
    guards: [],
    payload: {},
    fightPlan: {},
    levelByClass: {},
    ratingByClass: {},
    slot: 0,
    minMana: 0,
    beats: 0,
  },
  spells: {
    name: "",
    kind: "spell",
    handlerId: "",
    target: "",
    minPosition: "",
    nounDamage: "",
    functionName: "",
    guards: [],
    payload: {},
    levelByClass: {},
    ratingByClass: {},
    slot: 0,
    minMana: 0,
    beats: 0,
    affectData: [],
    lambdas: [],
  },
  commands: {
    name: "",
    message: "",
    role: "",
    usage: "",
    skillId: "",
    shortcuts: "",
    position: "",
    log: "",
    help: "",
    level: "",
    payload: {},
    guards: [],
    lambdas: [],
    enabled: true,
    pipeline: false,
    maxArguments: 0,
  },
  socials: {
    name: "",
    charNoArg: "",
    othersNoArg: "",
    charFound: "",
    othersFound: "",
    victFound: "",
    charNotFound: "",
    charAuto: "",
    othersAuto: "",
  },
  helps: {
    level: 0,
    keyword: "",
    text: "",
  },
  game: {
    kind: "",
    status: "",
    version: {},
    enums: {},
    attributeBonuses: {},
    classes: {},
    races: {},
    pcRaces: {},
    wiznetTable: {},
    groups: {},
    titles: {},
    itemTable: {},
    weapons: {},
    attacks: {},
    liquids: {},
    integrity: {},
    denyList: [],
  },
};

export const preferredEditableResourceFields: Record<string, string[]> = {
  items: [
    "id",
    "areaId",
    "vnum",
    "name",
    "shortDescription",
    "longDescription",
    "material",
    "itemType",
    "extraFlags",
    "wearFlags",
    "value0",
    "value1",
    "value2",
    "value3",
    "value4",
    "level",
    "weight",
    "cost",
    "condition",
    "affectData",
    "extraDescription",
  ],
  shops: [
    "id",
    "areaId",
    "keeper",
    "buyType0",
    "buyType1",
    "buyType2",
    "buyType3",
    "buyType4",
    "profitBuy",
    "profitSell",
    "openHour",
    "closeHour",
    "comment",
  ],
  resets: ["id", "areaId", "command", "arg1", "arg2", "arg3", "arg4", "comment"],
  specials: ["id", "areaId", "mobVnum", "name", "comment", "specialFunction"],
  classes: [
    "id",
    "name",
    "whoName",
    "primaryAttribute",
    "startingWeapon",
    "baseGroup",
    "defaultGroup",
    "skillAdept",
    "thac0_00",
    "thac0_32",
    "hpMin",
    "hpMax",
    "fMana",
  ],
  races: [
    "id",
    "name",
    "size",
    "skills",
    "classMultiplier",
    "points",
    "str",
    "maxStr",
    "INT",
    "maxInt",
    "con",
    "maxCon",
    "wis",
    "maxWis",
    "dex",
    "maxDex",
  ],
  skills: [
    "id",
    "name",
    "kind",
    "handlerId",
    "target",
    "minPosition",
    "nounDamage",
    "fightExecutor",
    "guards",
    "payload",
    "fightPlan",
    "levelByClass",
    "ratingByClass",
    "slot",
    "minMana",
    "beats",
  ],
  spells: [
    "id",
    "name",
    "kind",
    "handlerId",
    "target",
    "minPosition",
    "nounDamage",
    "functionName",
    "guards",
    "payload",
    "levelByClass",
    "ratingByClass",
    "slot",
    "minMana",
    "beats",
    "affectData",
    "lambdas",
  ],
  commands: [
    "id",
    "name",
    "message",
    "role",
    "usage",
    "skillId",
    "shortcuts",
    "position",
    "log",
    "help",
    "level",
    "payload",
    "guards",
    "lambdas",
    "enabled",
    "pipeline",
    "maxArguments",
  ],
  socials: [
    "id",
    "name",
    "charNoArg",
    "othersNoArg",
    "charFound",
    "othersFound",
    "victFound",
    "charNotFound",
    "charAuto",
    "othersAuto",
  ],
  helps: ["id", "level", "keyword", "text"],
  game: [
    "id",
    "kind",
    "status",
    "version",
    "enums",
    "attributeBonuses",
    "classes",
    "races",
    "pcRaces",
    "wiznetTable",
    "groups",
    "titles",
    "itemTable",
    "weapons",
    "attacks",
    "liquids",
    "integrity",
    "denyList",
  ],
};
