import type { ApiResource, DesignerDraft, WorkQueueItem } from "./domain";
import { resourceIcons } from "./domain";

export const apiResources: ApiResource[] = [
  {
    kind: "skills",
    label: "Skills",
    endpoint: "/api/v1/skills",
    icon: resourceIcons.Swords,
    status: "Ready",
    summary: "Practice-driven abilities with checks, class ratings, mana, and combat plans.",
    fields: [
      "name",
      "kind",
      "handlerId",
      "target",
      "minPosition",
      "levelByClass",
      "ratingByClass",
      "checks",
      "fightPlan",
    ],
  },
  {
    kind: "spells",
    label: "Spells",
    endpoint: "/api/v1/spells",
    icon: resourceIcons.Sparkles,
    status: "Ready",
    summary: "Castable effects with targets, class costs, affect data, and function bindings.",
    fields: [
      "name",
      "kind",
      "handlerId",
      "target",
      "functionName",
      "affectData",
      "lambdas",
      "slot",
      "beats",
    ],
  },
  {
    kind: "settings",
    label: "Game Settings",
    endpoint: "/api/v1/game",
    icon: resourceIcons.Settings2,
    status: "Drafting",
    summary: "Shared enums and configuration tables used by skills, spells, items, races, and classes.",
    fields: ["version", "enums", "classes", "races", "groups", "weapons", "attacks", "integrity"],
  },
  {
    kind: "areas",
    label: "Areas",
    endpoint: "/api/v1/areas",
    icon: resourceIcons.Castle,
    status: "Ready",
    summary: "Author-owned world containers that connect rooms, mobiles, objects, shops, resets, and specials.",
    fields: ["author", "name", "vnum", "suggestedLevelRange", "rooms", "mobiles", "objects", "resets"],
  },
  {
    kind: "rooms",
    label: "Rooms",
    endpoint: "/api/v1/rooms",
    icon: resourceIcons.BookOpen,
    status: "Ready",
    summary: "Navigable locations with descriptions, exits, sector types, flags, spawn behavior, and mobiles.",
    fields: ["areaId", "vnum", "name", "description", "exits", "sectorType", "roomFlags", "mobiles"],
  },
  {
    kind: "mobiles",
    label: "Mobiles",
    endpoint: "/api/v1/mobiles",
    icon: resourceIcons.Bot,
    status: "Ready",
    summary: "NPC definitions with race, dice, positions, flags, alignment, wealth, and combat stats.",
    fields: ["areaId", "vnum", "name", "race", "level", "hitDice", "damageDice", "flags", "statusFlags"],
  },
  {
    kind: "items",
    label: "Items",
    endpoint: "/api/v1/items",
    icon: resourceIcons.Boxes,
    status: "Ready",
    summary: "Objects with material, item type, wear flags, values, affects, descriptions, and economy data.",
    fields: ["areaId", "vnum", "name", "itemType", "wearFlags", "value0", "affectData", "cost"],
  },
  {
    kind: "communication",
    label: "Communication",
    endpoint: "/api/v1/socials",
    icon: resourceIcons.MessageSquareText,
    status: "Ready",
    summary: "Socials, commands, and help copy that shape how players communicate and discover actions.",
    fields: ["name", "charNoArg", "othersNoArg", "charFound", "victFound", "usage", "help"],
  },
];

export const initialDraft: DesignerDraft = {
  name: "ember ward",
  kind: "spells",
  areaId: "midgaard",
  target: "defensive",
  level: 12,
  notes: "Absorbs a small amount of fire damage and teaches low-level casters mitigation timing.",
};

export const workQueue: WorkQueueItem[] = [
  {
    id: "wf-1021",
    title: "Finish offensive skill checks",
    area: "Skills",
    resource: "skills",
    status: "Drafting",
    owner: "Design",
  },
  {
    id: "wf-1022",
    title: "Map eastern marsh room exits",
    area: "World",
    resource: "rooms",
    status: "Planned",
    owner: "Builder",
  },
  {
    id: "wf-1023",
    title: "Normalize social message variants",
    area: "Communication",
    resource: "communication",
    status: "Needs API",
    owner: "Content",
  },
  {
    id: "wf-1024",
    title: "Review item wear flag editor",
    area: "Items",
    resource: "items",
    status: "Drafting",
    owner: "Design",
  },
];
