import type { ApiResource, DesignerDraft, WorkQueueItem } from "./domain/types";
import { resourceIcons } from "./domain/types";

export const apiResources: ApiResource[] = [
  {
    kind: "skills",
    label: "Skills",
    endpoint: "/api/v1/skills",
    icon: resourceIcons.Swords,
    status: "Ready",
    summary: "Practice-driven abilities with checks, class ratings, mana, and combat plans.",
    fields: [
      "name",
      "kind",
      "handlerId",
      "target",
      "minPosition",
      "levelByClass",
      "ratingByClass",
      "checks",
      "fightPlan",
    ],
  },
  {
    kind: "spells",
    label: "Spells",
    endpoint: "/api/v1/spells",
    icon: resourceIcons.Sparkles,
    status: "Ready",
    summary: "Castable effects with targets, class costs, affect data, and function bindings.",
    fields: [
      "name",
      "kind",
      "handlerId",
      "target",
      "functionName",
      "affectData",
      "lambdas",
      "slot",
      "beats",
    ],
  },
  {
    kind: "settings",
    label: "Game Settings",
    endpoint: "/api/v1/game",
    icon: resourceIcons.Settings2,
    status: "Drafting",
    summary: "Shared enums and configuration tables used by skills, spells, items, races, and classes.",
    fields: ["version", "enums", "classes", "races", "groups", "weapons", "attacks", "integrity"],
  },
  {
    kind: "game",
    label: "Game Data",
    endpoint: "/api/v1/game",
    icon: resourceIcons.Gamepad2,
    status: "Ready",
    summary: "Versioned ruleset data with enums, class tables, race tables, groups, combat tables, and integrity metadata.",
    fields: ["kind", "status", "version", "enums", "attributeBonuses", "classes", "races", "integrity"],
  },
  {
    kind: "areas",
    label: "Areas",
    endpoint: "/api/v1/areas",
    icon: resourceIcons.Castle,
    status: "Ready",
    summary: "Author-owned world containers that connect rooms, mobiles, objects, shops, resets, and specials.",
    fields: ["author", "name", "vnum", "suggestedLevelRange", "rooms", "mobiles", "objects", "resets"],
  },
  {
    kind: "rooms",
    label: "Rooms",
    endpoint: "/api/v1/rooms",
    icon: resourceIcons.BookOpen,
    status: "Ready",
    summary: "Navigable locations with descriptions, exits, sector types, flags, spawn behavior, and mobiles.",
    fields: ["areaId", "vnum", "name", "description", "exits", "sectorType", "roomFlags", "mobiles"],
  },
  {
    kind: "mobiles",
    label: "Mobiles",
    endpoint: "/api/v1/mobiles",
    icon: resourceIcons.Bot,
    status: "Ready",
    summary: "NPC definitions with race, dice, positions, flags, alignment, wealth, and combat stats.",
    fields: ["areaId", "vnum", "name", "race", "level", "hitDice", "damageDice", "flags", "statusFlags"],
  },
  {
    kind: "items",
    label: "Items",
    endpoint: "/api/v1/items",
    icon: resourceIcons.Boxes,
    status: "Ready",
    summary: "Objects with material, item type, wear flags, values, affects, descriptions, and economy data.",
    fields: [
      "areaId",
      "vnum",
      "name",
      "shortDescription",
      "longDescription",
      "material",
      "itemType",
      "extraFlags",
      "wearFlags",
      "value0",
      "value1",
      "value2",
      "value3",
      "value4",
      "level",
      "weight",
      "cost",
      "condition",
      "affectData",
      "extraDescription",
    ],
  },
  {
    kind: "shops",
    label: "Shops",
    endpoint: "/api/v1/shops",
    icon: resourceIcons.Boxes,
    status: "Ready",
    summary: "Shop definitions with keepers, accepted item types, markup, markdown, hours, and builder comments.",
    fields: [
      "areaId",
      "keeper",
      "buyType0",
      "buyType1",
      "buyType2",
      "buyType3",
      "buyType4",
      "profitBuy",
      "profitSell",
      "openHour",
      "closeHour",
      "comment",
    ],
  },
  {
    kind: "resets",
    label: "Resets",
    endpoint: "/api/v1/resets",
    icon: resourceIcons.FlameKindling,
    status: "Ready",
    summary: "Area reset commands and arguments that repopulate rooms, mobiles, objects, and equipment.",
    fields: ["areaId", "command", "arg1", "arg2", "arg3", "arg4", "comment"],
  },
  {
    kind: "specials",
    label: "Specials",
    endpoint: "/api/v1/specials",
    icon: resourceIcons.ScrollText,
    status: "Ready",
    summary: "Mobile special procedure bindings with area ownership, mob vnums, comments, and function names.",
    fields: ["areaId", "mobVnum", "name", "comment", "specialFunction"],
  },
  {
    kind: "classes",
    label: "Classes",
    endpoint: "/api/v1/classes",
    icon: resourceIcons.GraduationCap,
    status: "Ready",
    summary: "Playable class definitions with attribute focus, weapon, groups, mana behavior, adeptness, THAC0, and hit points.",
    fields: [
      "name",
      "whoName",
      "primaryAttribute",
      "startingWeapon",
      "baseGroup",
      "defaultGroup",
      "skillAdept",
      "thac0_00",
      "thac0_32",
      "hpMin",
      "hpMax",
      "fMana",
    ],
  },
  {
    kind: "races",
    label: "Races",
    endpoint: "/api/v1/races",
    icon: resourceIcons.UsersRound,
    status: "Ready",
    summary: "Playable race definitions with size, default skills, class multipliers, point cost, and stat ranges.",
    fields: [
      "name",
      "size",
      "skills",
      "classMultiplier",
      "points",
      "str",
      "maxStr",
      "INT",
      "maxInt",
      "con",
      "maxCon",
      "wis",
      "maxWis",
      "dex",
      "maxDex",
    ],
  },
  {
    kind: "commands",
    label: "Commands",
    endpoint: "/api/v1/commands",
    icon: resourceIcons.ScrollText,
    status: "Ready",
    summary: "Command definitions with roles, usage, pipeline payloads, guards, lambdas, and argument limits.",
    fields: ["name", "message", "role", "usage", "skillId", "position", "payload", "guards", "enabled"],
  },
  {
    kind: "helps",
    label: "Help",
    endpoint: "/api/v1/helps",
    icon: resourceIcons.CircleHelp,
    status: "Ready",
    summary: "Help entries with minimum level, keyword, and body text.",
    fields: ["level", "keyword", "text"],
  },
  {
    kind: "socials",
    label: "Socials",
    endpoint: "/api/v1/socials",
    icon: resourceIcons.MessageSquareText,
    status: "Ready",
    summary: "Social command message variants for no-arg, target-found, not-found, and self-target cases.",
    fields: ["name", "charNoArg", "othersNoArg", "charFound", "othersFound", "victFound", "charNotFound"],
  },
  {
    kind: "notes",
    label: "Notes",
    endpoint: "/api/v1/notes",
    icon: resourceIcons.NotebookText,
    status: "Ready",
    summary: "In-game notes with sender, recipient list, subject, body, type, and date stamps.",
    fields: ["type", "sender", "date", "toList", "subject", "text", "dateStamp"],
  },
  {
    kind: "communication",
    label: "Communication",
    endpoint: "/api/v1/socials",
    icon: resourceIcons.MessageSquareText,
    status: "Ready",
    summary: "Socials, commands, and help copy that shape how players communicate and discover actions.",
    fields: ["name", "charNoArg", "othersNoArg", "charFound", "victFound", "usage", "help"],
  },
];

export const initialDraft: DesignerDraft = {
  name: "ember ward",
  kind: "spells",
  areaId: "midgaard",
  target: "defensive",
  level: 12,
  notes: "Absorbs a small amount of fire damage and teaches low-level casters mitigation timing.",
};

export const workQueue: WorkQueueItem[] = [
  {
    id: "wf-1021",
    title: "Finish offensive skill checks",
    area: "Skills",
    resource: "skills",
    status: "Drafting",
    owner: "Design",
  },
  {
    id: "wf-1022",
    title: "Map eastern marsh room exits",
    area: "World",
    resource: "rooms",
    status: "Planned",
    owner: "Builder",
  },
  {
    id: "wf-1023",
    title: "Normalize social message variants",
    area: "Communication",
    resource: "communication",
    status: "Needs API",
    owner: "Content",
  },
  {
    id: "wf-1024",
    title: "Review item wear flag editor",
    area: "Items",
    resource: "items",
    status: "Drafting",
    owner: "Design",
  },
];
